### ISSUE TITLE
Giving Hatchers more guidance in the Info Page

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#185]
From CEO of Blockscience:

Was thinking some guidance on the implications of numbers of hatchers would be valuable here and even if it's "if you're not sure or you find this question confusion, just pick 5 and move on, you can always change this later" 

![Screen Shot 2021-03-02 at 11.27.03 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/f456120f-99ad-48dc-9dcb-42690a75b6c7)

![Screen Shot 2021-03-02 at 11.27.16 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/a569442c-fc69-41f7-85fd-9ea7f8aa5f84)

Same above; if I do not know the implications of my choice I would appreciate more guidance; the entire idea of "proposals" could be more explicitely described somewhere in the intro section maybe; most people will not have a mental model of how proposals fit into the economy vision

**Comment by markoprljic** [comment]
Content needed to update text with more info of the implications of users choice.

**Comment by laurenluz** [comment]
@mendesfabio Can you help to update the text in the "More Info" sections for Hatchers and Inital Proposals? New text below:

'Founding Members - “Hatchers”

“Hatchers” are the founding members of the RadicalxChange Commons. They are the first to take responsibility over the Commons, prioritizing the needs of the community.

Only trusted experts who accept accountability for upholding the values and honorable intentions of the community should be chosen to be the founding members of your RadicalxChange Commons.

A larger number of Hatchers means there will be a larger amount of initial funds in the Funding Pool (to fund projects) and the RxC reserve (to give value to the RxC token). However, a larger number of Hatchers may make the token price more volatile after the initial vesting period. Also consider that the success of the Commons depends on the success of projects which is affected by the number of proposals and the ability for proposals to receive enough support (conviction) to be passed.

YOU must decide how many Hatchers are needed for the RadicalxChange community to initiate their Commons...'

'Proposals

It was evident from the introductions round at RadicalxChange’s new chapter kickoff in Barcelona that there are many great projects to create value for and by the community, and for the global RadicalxChange movement. To determine where to initially focus their efforts, they will collect a series of proposals and then vote on whether or not to accept them.

RadicalxChange project organizers can submit proposals to launch an initiative to request funding for a reimbursement of expenses for their projects. The RadicalxChange Commons can then vote on whether or not to accept it.

The initial conditions are critical to understand because they determine the outcomes for complex systems. If there are only a few Hatchers and a large number of proposals, it may be difficult for proposals to receive enough conviction to be passed. If there are a large number of Hatchers and only a few initial proposals, even if all the proposals are passed initially it will take some time for new ones to be generated and implemented. This means that progress towards saving the future will be slow and people may begin to lose faith in the Commons.

There are many factors to consider when making the optimal choice for your Commons. You must determine how many proposals will be collected for when the Hatchers start their voting.'

FYI - "More info" text is in this google doc: https://docs.google.com/document/d/1fT1oMKlV4AMrzcH5sk1uo5xUb_RLykYF3GnxkkTI5LU/edit#

Thanks to @marthendalnunes for providing background info so I could write this up!
