### ISSUE TITLE
Create a text explanation for what is Funding Pool 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#39]
This is the amount of funding that is allocated to support RxC projects, it is initialized by the Hatch tribute grows via the exit tribute and shrinks when projects are funded.

**Comment by laurenluz** [comment]
Funding Pool: the portion of total community funds that is allocated to support RxC projects. The funding pool is initialized by the starting investment of the Hatchers (the Hatch tribute). When projects are approved by the community, the funds required are withdrawn from the funding pool. The funding pool grows when members choose to sell their tokens because a portion of their withdrawal, called “the exit tribute”, is fed back into the community funding pool.
