### ISSUE TITLE
Should we remove RxC from the sub header too?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#92]
For sure the Title had to change... I'm ok with it in the subheader... but it will be changed when we get level 2 up, so I would sort of prefer a better sub heading assuming that eventuality... but it can be for the next release... and you can veto me on this Dani

![Screen Shot 2021-01-05 at 7.55.20 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8d3e809f-08a3-4cb7-8b83-43dd0c59e992)

**Comment by Danibelle** [comment]
I agree!  The title should be "The Commons Simulator" .. 
Subtitle is what would change per leap so in this one it's the RadicalxChange Commons..

I also think it would be okay to take out RxC from this page entirely, because we find out later in the narrative that it's for the RadicalxChange Commons... this is introducing the simulator and I really liked the subtitle as:

Designing a Regenerative Commons with the power of cadCAD.

**Comment by mendesfabio** [comment]
> Designing a Regenerative Commons with the power of cadCAD.

Looks good! If we have thumbs up from @GriffGreen, I add to Vue.

**Comment by GriffGreen** [comment]
"Designing a Regenerative Commons with the power of cadCAD."
